channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.21.2
  - cloudpickle==3.1.1
  - numpy==2.2.4
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
